version: '3'

services:
  php:
    build: ./Docker/php
    volumes:
      - ./Docker/composer:/usr/local/bin/composer
      - ./:/var/www/html
      - ./Docker/php/conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    environment:
      - PHP_IDE_CONFIG=serverName=docker
      - XDEBUG_MODE=debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8004:80"
    volumes:
      - ./public:/var/www/html/public
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33010:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: 1
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge